### ISSUE TITLE
missing exports?

### ISSUE THREAD

**Issue by tjapa** [dohomi/tamagui-kitchen-sink#10]
I'm trying to import the LmInput component but I'm getting the following error:

```
"tamagui-extras"` has no exported member 'LmInput'. Did you mean 'Input'?
```

The same happens when a try this import:

```tsx
import {LmFormRhfProvider, LmInputRhf, LmSliderRhf, LmSubmitButtonRhf} from "tamagui-extras";
```

I'm using the version 0.12.2.

**Comment by dohomi** [comment]
sorry I rework the entire structure of this lib, please stick to 0.11.x for now. I will update README because from 0.12.x I do more granular exports from 0.12 onwards

**Comment by tjapa** [comment]
Oh, I understood. Thank you!

**Comment by dohomi** [comment]
@tjapa OK please upgrade to 0.12.5 and re-import all `Lm*` components where you codebase complains. I added an upgrade guide: https://github.com/dohomi/tamagui-kitchen-sink#upgrade-guide--012

**Comment by dohomi** [comment]
Please report back if you face any issues with the new folder structure

**Comment by tjapa** [comment]
@dohomi works now!
