### ISSUE TITLE
Invalid export from package tamagui-extras: function `getComponentStaticConfigByName`

### ISSUE THREAD

**Issue by HarunKilic** [dohomi/tamagui-kitchen-sink#15]
I'm getting this error at startup, which is non-breaking error: 

```transform[stderr]: Tamagui failed getting from tamagui-extras (Disable error by setting environment variable TAMAGUI_DISABLE_WARN_DYNAMIC_LOAD=1)
transform[stderr]: Error: Invalid export from package tamagui-extras: function
transform[stderr]:     at getComponentStaticConfigByName```

Using latest version `0.12.13`

**Comment by dohomi** [comment]
@HarunKilic can you try 0.14.0 and also update to the latest Tamagui 1.14.4 version? I think that got fixed in the most recent release

**Comment by HarunKilic** [comment]
Just tried, same error :/

**Comment by dohomi** [comment]
Do you have a repo to look at?

**Comment by HarunKilic** [comment]
@dohomi it's a private repo. I'll invite you :)

**Comment by dohomi** [comment]
@HarunKilic this is a starter you haven't initiated with tamagui starter? I have not enough time to dig into that code base I havent even been able to start the dev server.

I would suggest to follow the official Tamagui template and then migrate your code into the expo folder and step by step reduce all the overhead suggested to use Solito. Start with a public repo and then later on you can migrate working code into your private repo. Thats why this tamagui-kitchen-sink project exists in the first place. It is 1. the dev environment for the tamagui-extras package but also to publicly tackle issues

**Comment by dohomi** [comment]
you can also clone this kitchen sink as a starter and remove the "ui" folder

**Comment by HarunKilic** [comment]
The project is initiated with tamagui starter, using this repo: https://github.com/ivopr/tamagui-expo
I do not need the web app as it's not part of the project. 

I'll try to create a minimal reproduction.

**Comment by HarunKilic** [comment]
Wow, after researching for several hours. I found the issue. 
Added this to babel: 
```
        "@tamagui/babel-plugin",
        {
          components: ["tamagui-extras", "tamagui"],
                      ---------- ^ THIS --------
```

And THAT was the issue!

**Comment by dohomi** [comment]
great that you found it. So as described in the tamagui docs every design system built with tamagui needs to be part of that: https://tamagui.dev/docs/guides/design-systems#react-native
So be aware when you might extend to NextJS or Webpack that thats important there as well

**Comment by dohomi** [comment]
I will add it to the documentation!
