### ISSUE TITLE
PopperArrow must be within Popper

### ISSUE THREAD

**Issue by HarunKilic** [dohomi/tamagui-kitchen-sink#16]
Using LmAutocomplete in Expo leads to this error: 

```
Error: `PopperArrow` must be used within `Popper`

This error is located at:
    in PopperArrow2 (created by PopoverArrow)
    in PopoverArrow (created by LmPopover)
``` 
    
    Using version: `0.12.13`

**Comment by dohomi** [comment]
This might be some error when the LmAutocomplete changes to sheet? I currently suffer from the iOS XCode issue that locally my entire expo dev is not starting at all.. Will try to solve this asap

**Comment by HarunKilic** [comment]
This happens as soon as the component is created

**Comment by dohomi** [comment]
@HarunKilic can you check out 0.14.0? I reworked date and autocomplete components and also fixed a few other minor bugs with Expo. Hopefully now the app compiles correctly

**Comment by HarunKilic** [comment]
Unfortunately same error

**Comment by HarunKilic** [comment]
I've added minimal reproduction of the error: https://github.com/HarunKilic/tamagui-extras-repro

**Comment by dohomi** [comment]
@HarunKilic can you see if the issue is solved with the new `@tamagui-extras/form`?

**Comment by dohomi** [comment]
will close this for now feel free to re-open
