### ISSUE TITLE
LmSelect has blank input when selected

### ISSUE THREAD

**Issue by HarunKilic** [dohomi/tamagui-kitchen-sink#17]
The LmSelect is blank when selecting an item from dropdown. 
Also reproduced in demo: https://tamagui-extras.vercel.app/?path=/story/form-select--inline

**Comment by dohomi** [comment]
@HarunKilic ahh, yeah because the value is meant to be populated via `<LmSelectRhf />`. The main intention was writing this form library especially for the integration with `react-hook-form`, maybe I should even don't export the non-rhf components. Do you have any thoughts?

**Comment by dohomi** [comment]
fixed in the next release

**Comment by dohomi** [comment]
fixed in 0.13.0
