### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by rdewolff** [dohomi/tamagui-kitchen-sink#2]
Adding the infos provided in the readme does not work for me.
Are these up to date?

The info from URL provided https://github.com/dohomi/tamagui-kitchen-sink/blob/master/apps/next/next.config.js#L16 differ from the one in the [readme](https://github.com/dohomi/tamagui-kitchen-sink/blob/master/readme.md).

### Example next.config.js
```
const transpilePackages = [
  'solito',
  'react-native-web',
  'react-native',
  'expo-linking',
  'expo-constants',
  'expo-modules-core',
  'expo-document-picker',
  'expo-av',
  'tamagui-phosphor-icons',
  // 'tamagui-extras'
  // '@expo/vector-icons',
]
```

### Readme
```
require('next-transpile-modules')(
    [
        'solito',
        'react-native-web',
        'expo-linking',
        'expo-constants',
        'expo-modules-core',
        'expo-document-picker',
        'expo-asset',
        'expo-av',
        '@my/config',
        'tamagui-extras'
    ]
)
```

Which packages need to be transpiled exactly for this lib to work?

**Comment by dohomi** [comment]
@rdewolff sorry the readme is outdated, I will link it to the next.config.js file that there won't be any confusion
