### ISSUE TITLE
App crashes on Android when LmInputRhf has isPassword={true}

### ISSUE THREAD

**Issue by e-aleixandre** [dohomi/tamagui-kitchen-sink#21]
My app is crashing instantly when loading a form with an `LmInputRhf` with `isPassword={true}` with the following error:

```
Error while updating property 'height' in shadow node of type: RCTView

null

Unknown value: 20px
```

Expo console shows no errors. That error just flashes on the Android and the app instantly closes. I don't know if that has something to do with @tamagui-extras/form or it's a problem with the package versions I'm using.

**Comment by dohomi** [comment]
@e-aleixandre thanks for your report. Is it working in iOS? I will try to reproduce it

**Comment by dohomi** [comment]
I also threw out a new release which was fixing outstanding bundler issues. Do you have `@tamagui-extras/form` inside your babel config?

**Comment by e-aleixandre** [comment]
I do have it in babel's config. For now I have no way of testing in iOS, I will try to free up some space and install xcode. I don't think its a problem with the new release, it's been happening for a while. I updated to the latest version to check if it got fixed but no luck. 

babel.config.js
```
process.env.TAMAGUI_TARGET = 'native';

module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: [
      [
        '@tamagui/babel-plugin',
        {
          components: ['@tamagui-extras/core', '@tamagui-extras/form', 'tamagui'],
          config: './tamagui.config.ts',
          logTimings: true,
        },
      ],
      [
        'transform-inline-environment-variables',
        {
          include: 'TAMAGUI_TARGET',
        },
      ],
      'react-native-reanimated/plugin',
      require.resolve('expo-router/babel'),
    ],
  };
};
```

**Comment by dohomi** [comment]
@e-aleixandre so if you don't enable `isPassword` the components render as usual? If so, it would be helpful if you could elaborate which CSS rule (if its css..) crashes it. Following lines I suspect:
https://github.com/dohomi/tamagui-kitchen-sink/blob/master/packages/form/src/LmInput.tsx#L74
I can try to use integer only values at this particular spot, but I dont have an Android environment. Could you have a quick try if that throws the error?

**Comment by e-aleixandre** [comment]
Yes, if I don't enable `isPassword` it works good. Perhaps this issue is relevant https://github.com/facebook/react-native/issues/20206 . I think both height and right style attributes cause the error and should be fixed. Apparently iOS handles the exception properly and the app doesn't crash.

**Comment by dohomi** [comment]
Ok I will rewrite the part

**Comment by dohomi** [comment]
@e-aleixandre can you check if the newest release fixes your issue?

**Comment by e-aleixandre** [comment]
@dohomi It's fixed. Thanks.

**Comment by dohomi** [comment]
great!

**Comment by dohomi** [comment]
great!
