### ISSUE TITLE
Phosphor icons doubles js bundle size

### ISSUE THREAD

**Issue by ugened47** [dohomi/tamagui-kitchen-sink#22]
Hi! Thanks for such a good sprinkles for tamagui. I have a question if it's possible somehow to tree-shake unused phosphor-icons, as I see they significantly impact the js bundle. Thank you.
<img width="1664" alt="Screenshot 2023-04-24 at 19 07 28" src="https://user-images.githubusercontent.com/9214135/234057756-1f797dd8-6800-4b90-b61d-7a5b24699832.png">

**Comment by dohomi** [comment]
can you try https://github.com/dohomi/tamagui-kitchen-sink/blob/master/apps/next/next.config.js#L69 Is that NextJS?

**Comment by ugened47** [comment]
@dohomi this is one is expo bundle, not nextjs. So basically it adds 14 mb overhead to production aab/apk/ipa

**Comment by dohomi** [comment]
@ugened47 what are best practices in Expo to use libraries like Phosphor, Material Icons or any other library? Shouldn't there be any code split where only used icons will be part of the production bundle?

**Comment by dohomi** [comment]
I've seen that Expo has https://docs.expo.dev/guides/icons/ where they advise to use a font. I will probably cut a new release where I use no icon library and just cherry-pick the ones important for the library.

**Comment by dohomi** [comment]
@ugened47 I published a new version - please update to newest release 1.1.x. 
I removed the dependency to phosphor icons so you can remove the dependency entirely, as well as the next.config

**Comment by ugened47** [comment]
@dohomi awesome, thank you very much.
