### ISSUE TITLE
Datepicker doesn't fill width

### ISSUE THREAD

**Issue by tjapa** [dohomi/tamagui-kitchen-sink#23]
How do I make the datepicker fill the entire width like the fields above it in the image?
I don't know if this is a bug or it's my fault.

![image](https://user-images.githubusercontent.com/17579637/236355066-3c24b8f1-598a-43ab-9fb9-4dfbf3e35aab.png)

**Comment by dohomi** [comment]
Good catch, I published a new patch release to support `fullWidth` prop 
```tsx 
<LmDatepicker fullWidth />
```
Please let me know if that works for you

**Comment by tjapa** [comment]
It worked! Thanks!
