### ISSUE TITLE
No native ExponentConstants module found, are you sure the expo-constants's module is linked properly?

### ISSUE THREAD

**Issue by timothymiller** [dohomi/tamagui-kitchen-sink#24]
Great job on this project. It's clear you are an influential part of the Tamagui ecosystem.

## Description

When running or building the nextjs app in this monorepo, this error is logged to the console.

```
No native ExponentConstants module found, are you sure the expo-constants's module is linked properly?
```

Is this error benign? What do you make of it?

**Comment by dohomi** [comment]
hey @timothymiller thanks for your kind words. I see this warn as well, but still have no clue which dependency is triggering it. It also does not do any harm but I want to get rid of it as well :-)

**Comment by dohomi** [comment]
closing this issue for now as it seems not related to this package
