### ISSUE TITLE
LmAvatar is crashing Expo Go (Android)

### ISSUE THREAD

**Issue by Carbowix** [dohomi/tamagui-kitchen-sink#27]
I was using LmAvatar recently with the "letter" property and I noticed that it was crashing on Expo Go Android.
I checked the [source code](https://github.com/dohomi/tamagui-kitchen-sink/blob/89df92364a93b1e432f2e3be5dcef1ed285a2c18/packages/core/src/core/content/LmAvatar.tsx#L23) and found you were using `Text`, so I tried to change it to `Paragraph` and it worked fine again without any noticeable change in design.

Here's a screenshot of the error:
![image](https://github.com/dohomi/tamagui-kitchen-sink/assets/24420693/cd89e11b-781a-49ce-b134-c680f81b8635)

**Comment by dohomi** [comment]
hi @Carbowix thanks for your report I will have a look shortly and will fix is asap. I think changing it to `StyleableText` should do the trick but I will find out.

**Comment by dohomi** [comment]
Changed to Paragraph in the newest release
