### ISSUE TITLE
wrap svg with tamagui styled

### ISSUE THREAD

**Issue by clayrisser** [dohomi/tamagui-kitchen-sink#3]
Are you able to wrap the `Svg` and `SvgUri` components with tamagui? When I try they don't seem to work.

**Comment by dohomi** [comment]
@clayrisser I use phosphor icons and not SVGs, you might drop better a message in the Discord channel there might be other users working with SVGs

**Comment by dohomi** [comment]
will close this for now. I think its rather related to `tamagui` main repo
