### ISSUE TITLE
Show only one datepicker input when selecting a range.

### ISSUE THREAD

**Issue by tjapa** [dohomi/tamagui-kitchen-sink#31]
Is it possible to show only one datepicker input when selecting a range?

![image](https://github.com/dohomi/tamagui-kitchen-sink/assets/17579637/cf111940-3b50-4c1f-a0e9-2052a6bae65d)

**Comment by dohomi** [comment]
@tjapa I was working on consolidating the range into one field. Hope on the weekend I will get my hands on and finalise the efforts.

**Comment by dohomi** [comment]
@tjapa released like this: https://tamagui-extras.vercel.app/?path=/story/date-datepicker--range-picker

**Comment by tjapa** [comment]
@dohomi Thank you!
