### ISSUE TITLE
LmDatepicker doesn't work on Android.

### ISSUE THREAD

**Issue by tjapa** [dohomi/tamagui-kitchen-sink#32]
LmDatepicker doesn't work on Android.
I also tested the LmDatePickerRhf and it doesn't work, the values don't update when I select a date.
And the Range Picker is showing two inputs, already on the web only one appears, as expected

**Comment by dohomi** [comment]
@tjapa the Datepicker shows an entirely different component on `native`. 
https://github.com/dohomi/tamagui-kitchen-sink/blob/master/packages/date/src/datepicker/LmDatepicker.native.tsx#L1

You might need to check the requirements of the `react-native-modal-datetime-picker` library which is running under the hood.

I haven't checked the native version for a while as I primarily developed web first. Will monitor this but if you have time to debug let me know what you find.

**Comment by laforetcan** [comment]
I get the same error on iOS. 

I think it's related to this issue on `react-native-modal-datetime-picker` package

I have this issue: 
I'm using `tamagui-extras/date` that has react-native-modal-datetime-picker as peer dependency 

But I get this error: 
`requireNativeComponent: RNDateTimePicker was not found in the UIManager.
`
and when I install it manually on my expo app with `yarn add react-native-modal-datetime-picker @react-native-community/datetimepicker` 

I get the error: `Tried to register two views with the same name RNDateTimePicker`


Many thanks for your help and consideration! 

Maybe something to do with: 
https://github.com/mmazzarolo/react-native-modal-datetime-picker/issues/645

**Comment by dohomi** [comment]
Hey guys, I haven't been working with Expo for a bit - but as the react-native-modal-datetime-picker is been used did you guys install the dependencies (not sure should tamagui-extras handle it?
```
$ yarn add react-native-modal-datetime-picker @react-native-community/datetimepicker
```

**Comment by dohomi** [comment]
I add a new section to the readme for other users to have a better start using this library: https://github.com/dohomi/tamagui-kitchen-sink/blob/master/readme.md#installation--troubleshoot-expo
Closing the issue for now
