### ISSUE TITLE
Button color variants

### ISSUE THREAD

**Issue by sebastianstupak** [dohomi/tamagui-kitchen-sink#33]
Hey,

I am not quite sure if I am setting up the package wrong - but when using `colorVariant="primary"` on LmButton (LmSubmitButtonRhf) I don't get any color. Same in public storybook demo - I don't see any color variants, they are all the same.

Do I have to setup the colors myself in tamagui config? If so - how exactly?
`"@tamagui-extras/core": "^1.2.0"`
```tsx
<LmSubmitButtonRhf
	colorVariant="primary"
	onSubmit={handleSubmit}>
	{t("auth:signInSubmit")}
</LmSubmitButtonRhf>
```
![image](https://github.com/dohomi/tamagui-kitchen-sink/assets/100760888/125e17d2-4aca-4cd8-8eca-0a680f4d6978)

**Comment by dohomi** [comment]
you are right, there must have been changes to the underlying config. I will provide a fix asap

**Comment by dohomi** [comment]
fixed in the latest release. The package is now up-to-date with most recent tamagui version
