### ISSUE TITLE
Media/breakpoint specific styles

### ISSUE THREAD

**Issue by reck753** [dohomi/tamagui-kitchen-sink#38]
Just started using these extra (very) helpful components and they are awesome! Thanks!

I am currently using `date` component only and I have encountered a small issue. 
In my Tamagui config, I have different breakpoints and I don't have some of the default ones. For example, I don't have `xs` breakpoint.
This produces a warning for invalid prop in `LmMonth` component as it sets this `$xs={{ width: '100%' }}` in couple of places.

This doesn't break anything, it just doesn't apply that style in my case which also doesn't make a problem since the component works and looks decent even without it.

Could we have some kind of API in which we could modify the specific styles or in which we could have our custom breakpoints mappings?

**Comment by dohomi** [comment]
@reck753 that is quite interesting - I wrote the component set around the current theme of Tamagui and haven't thought about the use of an entire different breakpoint setup. Is there a way of using breakpoints like 
```
 <Stack width={250} $xs={{ width: '100%' }}>
```
when your lib is not having the $xs theme breakpoint setup? the reason behind the style is simply that on small devices the width has to spread for 100% of the viewport

**Comment by reck753** [comment]
Hi @dohomi 

Yes there is. You can use custom breakpoints the same way like the you would use the default ones, fully type safe. For example, I can have something like this:
```
<Stack width={250} $s={{ width: '100%' }}>
```

I thought of the solution for this, which wouldn't change much and which would be a non-breaking change:
We could introduce a `TamaguiExtrasProvider` which would have custom breakpoint mappings like so:
```
// infer keys from some Tamagui built-in type for easier maintenance
type Mappings = {
  "$xs": string,
  "$sm": string
  ...
} | undefined

<TamaguiExtrasProvider
  value={{
    "$xs": "$s",
    "$sm": "$m",
    "$md": "$l",
    "$lg": "$xl",
  }}
>
  ...
</TamaguiExtrasProvider>
```
and then have some helper function like this:
```
// infer from some Tamagui  built-in type
type ResponsiveStyle = StackProps["$xs"]

// infer keys from some Tamagui built-in type for easier maintenance
type ResponsiveStyles = {
  "$xs": ResponsiveStyle,
  "$sm": ResponsiveStyle
  ...
}

// Not sure how I would type this right now
type SomeReturnType = object | Record<string, ResponsiveStyle>

const responsiveStylesWithCustomBreakpoints: (styles: ResponsiveStyles, mappings: Mappings): SomeReturnType => {
  if (mappings !== undefined) {
    return Object.entries(styles).map((key, value) => (mappings[key], value)).reduce(x => {
      // In case of multiple breakpoints are mapped to same custom breakpoint
      //  To avoid having e.g. `s: {{ width: 10 }}` (mapped from xs) and `s: {{ height: 20 }}` (mapped from sm)
      // where the second one would override the first one and ignore the ` width: 10`
    })
  } else {
    return styles
  }
}
```
and finally in one of the components where we would have the responsive styles:
```
const LmMonth = () => {
  const mappings = TamaguiExtrasContext.use()
  
  <Stack width={250} {...(
    responsiveStylesWithCustomBreakpoints(
      { $sm: { width: "100%" } },
      mappings
    )
  )}>
    ...
  </Stack>
}
```

Since, mappings are optional, for everyone using the default breakpoint system, nothing would change and for  everyone using custom breakpoints (like me), we could just include a `TamaguiExtrasProvider` in the root of the app or around the component where we need it (in my example, around `date` component).

**Comment by dohomi** [comment]
A provider would be one way of handling it but I think I would rather like to try solving it with a prop. Currently it only affects the one component, a provider feels a bit like an overkill. I will try to provide a solution soon.

**Comment by dohomi** [comment]
@reck753 I solved this issue now for the Date component. You will still have trouble with the `LmGrid` component but then I rather recommend to just copy paste the component and apply your custom breakpoints.

Let me know if you still face trouble.

**Comment by reck753** [comment]
@dohomi I updated to `@tamagui-extras/date@1.9.0` and everything works alright. Thank you very much!
