### ISSUE TITLE
Inter font is not used in Storybook

### ISSUE THREAD

**Issue by la55u** [dohomi/tamagui-kitchen-sink#4]
Some fonts are not loading properly, it should be Inter but it's loading the System font. You can observe it here: [Alert story](https://tamagui-extras.vercel.app/?path=/story/ui-content-alert--basic)
However on the [Card story](https://tamagui-extras.vercel.app/?path=/story/ui-content-card--basic) it shows the correct Inter font. Could you add an example how to load fonts properly in Storybook with Tamagui? 

Thank you for this repo, it helped me a lot

**Comment by dohomi** [comment]
good catch I will look into this

**Comment by dohomi** [comment]
@la55u I used the wrong component for the Alert, now `<Paragraph>` is in use which uses `$body` fontFamily. You will find the imports of fonts [here](https://github.com/dohomi/tamagui-kitchen-sink/blob/master/apps/storybook-react/.storybook/preview.tsx#L4)
