### ISSUE TITLE
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNDatePicker' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes

### ISSUE THREAD

**Issue by barathiofficial** [dohomi/tamagui-kitchen-sink#43]
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNDatePicker' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes

This error occurs when adding @tamagui-extras/date to an expo managed project.
![image (1)](https://github.com/dohomi/tamagui-kitchen-sink/assets/80629680/8c95774c-4769-4cce-b90a-e2082932c4f3)

**Comment by barathiofficial** [comment]
I found this discussion

https://github.com/react-native-datetimepicker/datetimepicker/issues/808

**Comment by dohomi** [comment]
I encourage everyone to hop on https://tamagui.dev/bento. I will deprecated several components which are covered by the Tamagui team - one of them is the datepicker
