### ISSUE TITLE
Using static image assets

### ISSUE THREAD

**Issue by la55u** [dohomi/tamagui-kitchen-sink#6]
Could you please provide an example how one should use local image assets in the `ui` package with tamagui's `Image` component? I'm struggling to bundle an image with one of the components that can then be used in Storybook, web and native too.
Thank you

**Comment by dohomi** [comment]
@la55u use the `SolitoImage` component. I did a small example yesterday to play around with it:
https://github.com/dohomi/tamagui-kitchen-sink/blob/master/packages/ui/stories/components/content/LmAvatar.stories.tsx#L40s
https://solito.dev/usage/image
you need to make sure to add a loader prop for the resizing capabilities especially to overwrite the behaviour in Storybook

**Comment by la55u** [comment]
Thank you for looking into this, but I was specifically asking about _local_ image assets (not from a url) as I find it hard to configure how to include it in the bundle.

**Comment by dohomi** [comment]
@la55u check the official Discord channel where your question will raise more awareness: https://discord.com/channels/909986013848412191/1059973736603857037

I personally don't use local images so I don't have an answer for it. Its either a Tamagui or RN or SolitoImage question, this library will not do any magic with your image approach so you can decide which ever solution suits you best.
