### ISSUE TITLE
Unable to resolve "tamagui-phosphor-icons"

### ISSUE THREAD

**Issue by HarunKilic** [dohomi/tamagui-kitchen-sink#9]
I am using tamagui on bare expo application. Without next. 
After installing, I ran into following error: 
`Unable to resolve "tamagui-phosphor-icons" from "node_modules/tamagui-extras/dist/cjs/components/panels/LmDialog.js"`

Installed the package, and it was fixed. 

But then I've got another error: 
`Unable to resolve "solito/link" from "node_modules/tamagui-extras/dist/cjs/components/forms/LmLinkButton.js"`

Which I won't install as I am not using solito. 

Am I missing something?

**Comment by dohomi** [comment]
Hi @HarunKilic thanks for your report. `solito` and `tamagui-phosphor-icons` are part of the peerDependencies thats why they are required to be installed. I would need to split the package into multiple entry points to support your use case. 
If you install `solito` and never use the `LmLinkButton` the final bundle size of your application should not be affected.

**Comment by dohomi** [comment]
I updated the installation part https://github.com/dohomi/tamagui-kitchen-sink#installation

**Comment by HarunKilic** [comment]
Thanks, I did install solito and tried again, but something conflicted with Hermes. Will provide the error once I am home :)

**Comment by HarunKilic** [comment]
I am not sure if it's related to this package, but the error I get is: 
`TypeError: Cannot read property 'isFileUploadSupported' of null, js engine: hermes`

**Comment by dohomi** [comment]
@HarunKilic in v0.12.5 I improved code split with `tamagui-extras`. Now there should be no complains about `solito` as its moved to `tamagui-extras/link`
Can you try out 012.5, but you might need to adjust your imports as it is a breaking change described in https://github.com/dohomi/tamagui-kitchen-sink#upgrade-guide--012

**Comment by HarunKilic** [comment]
Sounds great! But seems like im getting another error now: 
`Unable to resolve "tamagui-extras/form"`
Trying to import LMSelect. 

Btw, regarding to the upgrade guide, shouldn't they all be imported from  `tamagui-extras` and not directly `tamagui`?

eg. `import {LmInputRhf, LmFormRhfProvider} from "tamagui/form"; // depends on react-hook-form`

**Comment by dohomi** [comment]
@HarunKilic are you using v0.12.9? If yes you should also make sure that `tamagui-extras` is part of the `transpileModules` of NextJS/Storybook. But I am also still battling around the compile step gives me big headache. I am close to remove the compile step entirely and just export the plugin as TypeScript module. 
Thanks for pointing out the typo inside of the upgrade guide will fix it now

**Comment by HarunKilic** [comment]
@dohomi 

Yes I am using the latest version. But I am not using nextjs, only expo application.

**Comment by dohomi** [comment]
@HarunKilic I commented https://github.com/dohomi/tamagui-kitchen-sink/issues/12#issuecomment-1500776378 seems expo does not respect the new structure of the lib.. I am fighting with this issue for past 2 days and unable to get the setup work right. Do you use TypeScript? I am thinking of dumping the build step and let people consume direct TS files

**Comment by dohomi** [comment]
closing in favor for #12
